name: Build Go Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Set up MinGW
        uses: msys2/setup-msys2@v2

      - name: Install UPX
        run: |
          choco install upx -y

      - name: Build Executable
        run: go build -ldflags="-s -w -H=windowsgui" -o SysInfo.exe

      - name: Strip Executable
        run: strip your_program.exe

      - name: Compress Executable with UPX
        run: upx --best --lzma SysInfo.exe

      - name: Test the exe file with cmd
        shell: cmd
        run: .\SysInfo.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compressed-executable
          path: SysInfo.exe

